displayName=Responsive Tooltips
author=Zachary Jacobson
description=Allows Jagex tooltips to instantly appear and prayer tooltips to be colored rectangles
tags=tooltips,descriptions,ui,interface,prayer,stats,attack styles,emotes,settings,worlds
version=1.0.1
plugins=com.responsivetooltips.ResponsiveTooltipsPlugin
build=standard